name = "fishy-email-worker"
main = "index.js"
compatibility_date = "2024-12-01"

compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "CHAT_KV"
id = "76187ff3858a4a8bae93667e0b6c2cf2"

[[send_email]]
name = "SEND_EMAIL"
