import jsPDF from 'jspdf';

export interface MeetingData {
  title: string;
  date: Date;
  duration?: number;
  summary: string;
  keyPoints: string[];
  actionItems: any[];
  keyDecisions: any[];
  transcription: string;
}

export function exportToMarkdown(meeting: MeetingData): string {
  const markdown = `# ${meeting.title}

**Date:** ${meeting.date.toLocaleDateString()}
${meeting.duration ? `**Duration:** ${Math.floor(meeting.duration / 60)} minutes\n` : ''}

## Summary

${meeting.summary}

## Key Points

${meeting.keyPoints.map((point, i) => `${i + 1}. ${point}`).join('\n')}

## Action Items

${meeting.actionItems.map((item, i) => {
  const assignee = item.assignee ? ` - **Assigned to:** ${item.assignee}` : '';
  const priority = item.priority ? ` - **Priority:** ${item.priority}` : '';
  return `${i + 1}. ${item.task}${assignee}${priority}`;
}).join('\n')}

## Key Decisions

${meeting.keyDecisions.map((decision, i) => {
  return `${i + 1}. **${decision.decision}**\n   ${decision.context}`;
}).join('\n\n')}

## Full Transcript

${meeting.transcription}

---
*Generated by MeetingNotes AI*
`;

  return markdown;
}

export function exportToPDF(meeting: MeetingData): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - 2 * margin;
  let yPosition = margin;

  // Helper function to add text with automatic page breaks
  const addText = (text: string, fontSize: number, isBold = false) => {
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');

    const lines = doc.splitTextToSize(text, maxWidth);

    lines.forEach((line: string) => {
      if (yPosition > pageHeight - margin) {
        doc.addPage();
        yPosition = margin;
      }
      doc.text(line, margin, yPosition);
      yPosition += fontSize * 0.5;
    });

    yPosition += 5; // Add spacing after block
  };

  // Title
  addText(meeting.title, 20, true);

  // Metadata
  addText(`Date: ${meeting.date.toLocaleDateString()}`, 12);
  if (meeting.duration) {
    addText(`Duration: ${Math.floor(meeting.duration / 60)} minutes`, 12);
  }
  yPosition += 5;

  // Summary
  addText('Summary', 16, true);
  addText(meeting.summary, 11);
  yPosition += 5;

  // Key Points
  addText('Key Points', 16, true);
  meeting.keyPoints.forEach((point, i) => {
    addText(`${i + 1}. ${point}`, 11);
  });
  yPosition += 5;

  // Action Items
  if (meeting.actionItems.length > 0) {
    addText('Action Items', 16, true);
    meeting.actionItems.forEach((item, i) => {
      const text = `${i + 1}. ${item.task}${item.assignee ? ` (${item.assignee})` : ''} [${item.priority || 'medium'}]`;
      addText(text, 11);
    });
    yPosition += 5;
  }

  // Key Decisions
  if (meeting.keyDecisions.length > 0) {
    addText('Key Decisions', 16, true);
    meeting.keyDecisions.forEach((decision, i) => {
      addText(`${i + 1}. ${decision.decision}`, 11, true);
      addText(decision.context, 10);
    });
    yPosition += 5;
  }

  // Transcript
  addText('Full Transcript', 16, true);
  addText(meeting.transcription, 10);

  return doc;
}

export function exportToNotion(meeting: MeetingData): any {
  // Notion API payload structure
  return {
    parent: { database_id: 'YOUR_NOTION_DATABASE_ID' }, // User would configure this
    properties: {
      Name: {
        title: [
          {
            text: {
              content: meeting.title,
            },
          },
        ],
      },
      Date: {
        date: {
          start: meeting.date.toISOString(),
        },
      },
      Duration: {
        number: meeting.duration ? Math.floor(meeting.duration / 60) : 0,
      },
    },
    children: [
      {
        object: 'block',
        type: 'heading_2',
        heading_2: {
          rich_text: [{ type: 'text', text: { content: 'Summary' } }],
        },
      },
      {
        object: 'block',
        type: 'paragraph',
        paragraph: {
          rich_text: [{ type: 'text', text: { content: meeting.summary } }],
        },
      },
      {
        object: 'block',
        type: 'heading_2',
        heading_2: {
          rich_text: [{ type: 'text', text: { content: 'Key Points' } }],
        },
      },
      ...meeting.keyPoints.map((point) => ({
        object: 'block',
        type: 'bulleted_list_item',
        bulleted_list_item: {
          rich_text: [{ type: 'text', text: { content: point } }],
        },
      })),
      {
        object: 'block',
        type: 'heading_2',
        heading_2: {
          rich_text: [{ type: 'text', text: { content: 'Action Items' } }],
        },
      },
      ...meeting.actionItems.map((item) => ({
        object: 'block',
        type: 'to_do',
        to_do: {
          rich_text: [
            { type: 'text', text: { content: `${item.task} (${item.priority || 'medium'})` } },
          ],
          checked: false,
        },
      })),
    ],
  };
}
